import { useQuery } from '@tanstack/react-query';
import { getPublicSettings, type PageHeroConfig, type PageHeroKey } from '../services/api';

const DEFAULT_HERO_CONFIGS: Record<PageHeroKey, PageHeroConfig> = {
    home: {
        enabled: true,
        title: 'Welcome to CampusWay',
        subtitle: 'Your gateway to university admissions, exams, and resources.',
        pillText: 'CampusWay',
        vantaEffect: 'halo',
        vantaColor: '#f59e0b',
        vantaBackgroundColor: '#1a0f00',
        gradientFrom: '#78350f',
        gradientTo: '#92400e',
        showSearch: false,
        searchPlaceholder: '',
        primaryCTA: { label: 'Explore Universities', url: '/universities' },
        secondaryCTA: { label: 'View Exams', url: '/exams' },
    },
    universities: {
        enabled: true,
        title: 'Explore Universities',
        subtitle: 'Find the perfect university for your academic journey.',
        pillText: 'Universities',
        vantaEffect: 'net',
        vantaColor: '#3b82f6',
        vantaBackgroundColor: '#0f172a',
        gradientFrom: '#1e3a5f',
        gradientTo: '#4338ca',
        showSearch: false,
        searchPlaceholder: '',
        primaryCTA: { label: '', url: '' },
        secondaryCTA: { label: '', url: '' },
    },
    news: {
        enabled: true,
        title: 'Admission News & Updates',
        subtitle: 'Stay informed with the latest admission news and announcements.',
        pillText: 'News',
        vantaEffect: 'globe',
        vantaColor: '#6366f1',
        vantaBackgroundColor: '#0c1222',
        gradientFrom: '#1e1b4b',
        gradientTo: '#312e81',
        showSearch: true,
        searchPlaceholder: 'Search news articles...',
        primaryCTA: { label: '', url: '' },
        secondaryCTA: { label: '', url: '' },
    },
    exams: {
        enabled: true,
        title: 'Online Exams',
        subtitle: 'Test your preparation with live and upcoming exams.',
        pillText: 'Exams',
        vantaEffect: 'waves',
        vantaColor: '#0ea5e9',
        vantaBackgroundColor: '#0c1929',
        gradientFrom: '#0c4a6e',
        gradientTo: '#1e40af',
        showSearch: false,
        searchPlaceholder: '',
        primaryCTA: { label: 'View Live Exams', url: '/exams' },
        secondaryCTA: { label: '', url: '' },
    },
    resources: {
        enabled: true,
        title: 'Learning Resources',
        subtitle: 'Access study materials, guides, and resources.',
        pillText: 'Resources',
        vantaEffect: 'cells',
        vantaColor: '#8b5cf6',
        vantaBackgroundColor: '#0f0a1e',
        gradientFrom: '#2e1065',
        gradientTo: '#4c1d95',
        showSearch: true,
        searchPlaceholder: 'Search resources...',
        primaryCTA: { label: '', url: '' },
        secondaryCTA: { label: '', url: '' },
    },
    subscriptionPlans: {
        enabled: true,
        title: 'Subscription Plans',
        subtitle: 'Choose the plan that fits your needs.',
        pillText: 'Premium',
        vantaEffect: 'net',
        vantaColor: '#a855f7',
        vantaBackgroundColor: '#0f0326',
        gradientFrom: '#4c1d95',
        gradientTo: '#7c3aed',
        showSearch: false,
        searchPlaceholder: '',
        primaryCTA: { label: 'Compare Plans', url: '/subscription-plans#compare' },
        secondaryCTA: { label: '', url: '' },
    },
    contact: {
        enabled: true,
        title: 'Contact Us',
        subtitle: "Have questions? We're here to help.",
        pillText: 'Support',
        vantaEffect: 'fog',
        vantaColor: '#6366f1',
        vantaBackgroundColor: '#0f172a',
        gradientFrom: '#1e293b',
        gradientTo: '#334155',
        showSearch: false,
        searchPlaceholder: '',
        primaryCTA: { label: '', url: '' },
        secondaryCTA: { label: '', url: '' },
    },
    about: {
        enabled: true,
        title: 'About CampusWay',
        subtitle: 'Learn about our mission to empower students across Bangladesh.',
        pillText: 'About Us',
        vantaEffect: 'clouds',
        vantaColor: '#60a5fa',
        vantaBackgroundColor: '#0f172a',
        gradientFrom: '#1e3a5f',
        gradientTo: '#1e40af',
        showSearch: false,
        searchPlaceholder: '',
        primaryCTA: { label: '', url: '' },
        secondaryCTA: { label: '', url: '' },
    },
    helpCenter: {
        enabled: true,
        title: 'Help Center',
        subtitle: 'Find answers, guides, and support for all your questions.',
        pillText: 'Support',
        vantaEffect: 'dots',
        vantaColor: '#34d399',
        vantaBackgroundColor: '#0a1a14',
        gradientFrom: '#064e3b',
        gradientTo: '#065f46',
        showSearch: false,
        searchPlaceholder: '',
        primaryCTA: { label: '', url: '' },
        secondaryCTA: { label: '', url: '' },
    },
    privacy: {
        enabled: true,
        title: 'Privacy Policy',
        subtitle: 'How we collect, use, and protect your personal information.',
        pillText: 'Privacy',
        vantaEffect: 'rings',
        vantaColor: '#94a3b8',
        vantaBackgroundColor: '#0f172a',
        gradientFrom: '#1e293b',
        gradientTo: '#334155',
        showSearch: false,
        searchPlaceholder: '',
        primaryCTA: { label: '', url: '' },
        secondaryCTA: { label: '', url: '' },
    },
    terms: {
        enabled: true,
        title: 'Terms of Service',
        subtitle: 'Our terms and conditions for using CampusWay services.',
        pillText: 'Terms',
        vantaEffect: 'rings',
        vantaColor: '#94a3b8',
        vantaBackgroundColor: '#0f172a',
        gradientFrom: '#1e293b',
        gradientTo: '#334155',
        showSearch: false,
        searchPlaceholder: '',
        primaryCTA: { label: '', url: '' },
        secondaryCTA: { label: '', url: '' },
    },
};

export function mergeHeroConfig(
    defaults: PageHeroConfig,
    serverConfig: Partial<PageHeroConfig> | undefined | null,
): PageHeroConfig {
    if (!serverConfig) return defaults;

    return {
        enabled: serverConfig.enabled ?? defaults.enabled,
        title: serverConfig.title || defaults.title,
        subtitle: serverConfig.subtitle || defaults.subtitle,
        pillText: serverConfig.pillText || defaults.pillText,
        vantaEffect: serverConfig.vantaEffect || defaults.vantaEffect,
        vantaColor: serverConfig.vantaColor || defaults.vantaColor,
        vantaBackgroundColor: serverConfig.vantaBackgroundColor || defaults.vantaBackgroundColor,
        gradientFrom: serverConfig.gradientFrom || defaults.gradientFrom,
        gradientTo: serverConfig.gradientTo || defaults.gradientTo,
        showSearch: serverConfig.showSearch ?? defaults.showSearch,
        searchPlaceholder: serverConfig.searchPlaceholder || defaults.searchPlaceholder,
        primaryCTA: {
            label: serverConfig.primaryCTA?.label || defaults.primaryCTA.label,
            url: serverConfig.primaryCTA?.url || defaults.primaryCTA.url,
        },
        secondaryCTA: {
            label: serverConfig.secondaryCTA?.label || defaults.secondaryCTA.label,
            url: serverConfig.secondaryCTA?.url || defaults.secondaryCTA.url,
        },
    };
}

export function usePageHeroSettings(pageKey: PageHeroKey): PageHeroConfig {
    const { data } = useQuery({
        queryKey: ['public-settings'],
        queryFn: async () => (await getPublicSettings()).data,
        staleTime: 5 * 60 * 1000,
    });

    const serverConfig = (data as any)?.pageHeroSettings?.[pageKey];
    const defaults = DEFAULT_HERO_CONFIGS[pageKey];

    return mergeHeroConfig(defaults, serverConfig);
}

export { DEFAULT_HERO_CONFIGS };
