import { useState, useCallback } from 'react';
import { X, Wand2, RefreshCw, AlertTriangle } from 'lucide-react';
import toast from 'react-hot-toast';
import { autoGenerate } from '../../../api/adminExamApi';
import { useQuestionSelector } from './QuestionSelectorContext';
import type { AutoGenerateResponse } from '../../../types/exam';

interface AutoGenerateDialogProps {
    open: boolean;
    onClose: () => void;
}

interface ShortageDetail {
    level: string;
    requested: number;
    available: number;
}

const DEFAULT_MARKS = 1;

export default function AutoGenerateDialog({ open, onClose }: AutoGenerateDialogProps) {
    const { dispatch } = useQuestionSelector();

    const [subject, setSubject] = useState('');
    const [category, setCategory] = useState('');
    const [easyCount, setEasyCount] = useState(0);
    const [mediumCount, setMediumCount] = useState(0);
    const [hardCount, setHardCount] = useState(0);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [shortages, setShortages] = useState<ShortageDetail[]>([]);

    const totalRequested = easyCount + mediumCount + hardCount;

    const reset = useCallback(() => {
        setSubject('');
        setCategory('');
        setEasyCount(0);
        setMediumCount(0);
        setHardCount(0);
        setError(null);
        setShortages([]);
    }, []);

    const handleClose = useCallback(() => {
        if (loading) return;
        reset();
        onClose();
    }, [loading, reset, onClose]);

    const handleSubmit = async () => {
        if (totalRequested === 0) {
            setError('Specify at least one question in the difficulty distribution.');
            return;
        }

        setLoading(true);
        setError(null);
        setShortages([]);

        try {
            const res: AutoGenerateResponse = await autoGenerate({
                subject: subject.trim() || undefined,
                moduleCategory: category.trim() || undefined,
                distribution: { easy: easyCount, medium: mediumCount, hard: hardCount },
                defaultMarksPerQuestion: DEFAULT_MARKS,
            });

            dispatch({
                type: 'BULK_ADD',
                questions: res.questions,
                defaultMarks: DEFAULT_MARKS,
            });

            toast.success(`Added ${res.questions.length} questions`);
            handleClose();
        } catch (err: unknown) {
            const message = extractErrorMessage(err);

            // Parse shortage details from error message
            const parsed = parseShortages(message);
            if (parsed.length > 0) {
                setShortages(parsed);
                setError('Insufficient questions in the bank for the requested distribution.');
            } else {
                setError(message);
            }
        } finally {
            setLoading(false);
        }
    };

    if (!open) return null;

    return (
        <div
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4"
            onClick={handleClose}
        >
            <div
                role="dialog"
                aria-modal="true"
                aria-label="Auto Generate Questions"
                className="w-full max-w-lg rounded-2xl border border-slate-200 bg-white shadow-2xl dark:border-slate-700/60 dark:bg-slate-900"
                onClick={(e) => e.stopPropagation()}
            >
                {/* Header */}
                <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200 dark:border-slate-700/60">
                    <div className="flex items-center gap-2">
                        <Wand2 className="w-5 h-5 text-indigo-500" />
                        <h2 className="text-base font-bold text-slate-900 dark:text-white">Auto Generate Questions</h2>
                    </div>
                    <button
                        onClick={handleClose}
                        disabled={loading}
                        className="p-1.5 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-100 dark:hover:text-white dark:hover:bg-white/5 transition disabled:opacity-50"
                        aria-label="Close"
                    >
                        <X className="w-5 h-5" />
                    </button>
                </div>

                <div className="p-6 space-y-5">
                    {/* Filters */}
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                        <label className="block">
                            <span className="text-xs font-semibold text-slate-600 dark:text-slate-300 uppercase tracking-wider">
                                Subject
                            </span>
                            <input
                                type="text"
                                value={subject}
                                onChange={(e) => setSubject(e.target.value)}
                                placeholder="All subjects"
                                className="mt-1 w-full px-3 py-2 rounded-xl border border-slate-200 bg-white text-sm text-slate-900 placeholder:text-slate-400 dark:border-slate-700/60 dark:bg-slate-900/80 dark:text-white dark:placeholder:text-slate-500 focus:outline-none focus:ring-2 focus:ring-indigo-500/40"
                            />
                        </label>
                        <label className="block">
                            <span className="text-xs font-semibold text-slate-600 dark:text-slate-300 uppercase tracking-wider">
                                Category
                            </span>
                            <input
                                type="text"
                                value={category}
                                onChange={(e) => setCategory(e.target.value)}
                                placeholder="All categories"
                                className="mt-1 w-full px-3 py-2 rounded-xl border border-slate-200 bg-white text-sm text-slate-900 placeholder:text-slate-400 dark:border-slate-700/60 dark:bg-slate-900/80 dark:text-white dark:placeholder:text-slate-500 focus:outline-none focus:ring-2 focus:ring-indigo-500/40"
                            />
                        </label>
                    </div>

                    {/* Difficulty Distribution */}
                    <div className="space-y-2">
                        <p className="text-xs font-semibold text-slate-600 dark:text-slate-300 uppercase tracking-wider">
                            Difficulty Distribution
                        </p>
                        <div className="grid grid-cols-3 gap-3">
                            <DifficultyInput
                                label="Easy"
                                color="emerald"
                                value={easyCount}
                                onChange={setEasyCount}
                            />
                            <DifficultyInput
                                label="Medium"
                                color="amber"
                                value={mediumCount}
                                onChange={setMediumCount}
                            />
                            <DifficultyInput
                                label="Hard"
                                color="rose"
                                value={hardCount}
                                onChange={setHardCount}
                            />
                        </div>
                        {totalRequested > 0 && (
                            <p className="text-xs text-slate-500 dark:text-slate-400 text-right">
                                Total: {totalRequested} question{totalRequested !== 1 ? 's' : ''}
                            </p>
                        )}
                    </div>

                    {/* Error / Shortage display */}
                    {error && (
                        <div className="rounded-xl border border-rose-200 bg-rose-50 dark:border-rose-500/30 dark:bg-rose-900/15 px-4 py-3 space-y-2">
                            <div className="flex items-center gap-2">
                                <AlertTriangle className="w-4 h-4 text-rose-500 shrink-0" />
                                <p className="text-sm text-rose-700 dark:text-rose-300">{error}</p>
                            </div>
                            {shortages.length > 0 && (
                                <div className="space-y-1 pl-6">
                                    {shortages.map((s) => (
                                        <p key={s.level} className="text-xs text-rose-600 dark:text-rose-400">
                                            <span className="capitalize font-medium">{s.level}</span>: requested {s.requested}, available {s.available}
                                        </p>
                                    ))}
                                </div>
                            )}
                        </div>
                    )}

                    {/* Actions */}
                    <div className="flex items-center justify-end gap-2 pt-1">
                        <button
                            onClick={handleClose}
                            disabled={loading}
                            className="px-4 py-2 rounded-xl text-sm text-slate-500 hover:text-slate-700 dark:text-slate-400 dark:hover:text-white transition disabled:opacity-50"
                        >
                            Cancel
                        </button>
                        <button
                            onClick={handleSubmit}
                            disabled={loading || totalRequested === 0}
                            className="px-5 py-2 rounded-xl bg-indigo-600 text-white text-sm font-bold flex items-center gap-2 hover:bg-indigo-500 disabled:opacity-60 transition"
                        >
                            {loading ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Wand2 className="w-4 h-4" />}
                            {loading ? 'Generating…' : 'Generate'}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
}

/* ── Difficulty count input ── */

function DifficultyInput({
    label,
    color,
    value,
    onChange,
}: {
    label: string;
    color: 'emerald' | 'amber' | 'rose';
    value: number;
    onChange: (v: number) => void;
}) {
    const colorMap = {
        emerald: 'border-emerald-300 bg-emerald-50 text-emerald-700 dark:border-emerald-500/30 dark:bg-emerald-900/15 dark:text-emerald-300',
        amber: 'border-amber-300 bg-amber-50 text-amber-700 dark:border-amber-500/30 dark:bg-amber-900/15 dark:text-amber-300',
        rose: 'border-rose-300 bg-rose-50 text-rose-700 dark:border-rose-500/30 dark:bg-rose-900/15 dark:text-rose-300',
    };

    return (
        <div className={`rounded-xl border p-3 text-center ${colorMap[color]}`}>
            <p className="text-xs font-semibold mb-1.5">{label}</p>
            <input
                type="number"
                min={0}
                value={value}
                onChange={(e) => onChange(Math.max(0, Number(e.target.value) || 0))}
                className="w-full text-center text-lg font-bold bg-transparent border-0 focus:outline-none focus:ring-0 [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none"
            />
        </div>
    );
}

/* ── Helpers ── */

function extractErrorMessage(err: unknown): string {
    if (err && typeof err === 'object') {
        const axiosErr = err as { response?: { data?: { message?: string; error?: string } }; message?: string };
        return (
            axiosErr.response?.data?.message ??
            axiosErr.response?.data?.error ??
            axiosErr.message ??
            'Auto-generation failed. Please try again.'
        );
    }
    return 'Auto-generation failed. Please try again.';
}

function parseShortages(message: string): ShortageDetail[] {
    const details: ShortageDetail[] = [];
    // Match patterns like "Insufficient easy questions: requested 5, available 2"
    const regex = /insufficient\s+(\w+)\s+questions?:\s*requested\s+(\d+),\s*available\s+(\d+)/gi;
    let match: RegExpExecArray | null;
    while ((match = regex.exec(message)) !== null) {
        details.push({
            level: match[1].toLowerCase(),
            requested: Number(match[2]),
            available: Number(match[3]),
        });
    }
    return details;
}
